### ISSUE TITLE
manifest does not work on acl 8.2, modern mode

### ISSUE THREAD

**Issue by hanshuebner** [gigamonkey/manifest#1]
Hi Peter,

I tried manifest with acl8.2 in modern mode on Linux - It does not work.  The index page with the systems displays properly, but the systems themselves respond with a 404 page.  Can you suggest anything to help me diagnose the problem?

Thanks,
Hans

**Comment by gigamonkey** [comment]
Use Common Lisp. ;-) (Probably the issue is that I take the name from
the url (which is lower case) and upcase it. I suppose I could try the
downcased name if it doesn't find a package under the upcased name.
Depends on whether I feel like being charitable to modern mode.

-Peter

On Thu, Dec 8, 2011 at 11:37 PM, Hans Hübner
reply@reply.github.com
wrote:

> Hi Peter,
> 
> I tried manifest with acl8.2 in modern mode on Linux - It does not work.  The index page with the systems displays properly, but the systems themselves respond with a 404 page.  Can you suggest anything to help me diagnose the problem?
> 
> Thanks,
> Hans
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gigamonkey/manifest/issues/1

## 

Peter Seibel
http://www.gigamonkeys.com/

**Comment by gigamonkey** [comment]
Should work now. Let me know if it doesn't.
